baseURL = "https://zeljko.dakic.com/"
languageCode = "en-us"
title = "Zeljko Dakic Is Doing Software In Chicago Blog"
theme = "internet-weblog"

SectionPagesMenu = "main"

[params]
   RSSSections = [ "Posts", "Microposts" ]
   Description = "Zeljko Dakic Is Doing Software In Chicago Blog"
   ShowCopyright = true
   RSSEnabled = true
   rssmicroposttitles = false


[author]
   Handle = "Zeljko"
   FirstName = "Zeljko"
   LastName = "Dakic"
   AboutPage = "https://dakic.com/"
   Location = "Chicago, IL, USA"

[taxonomies]
   tag = "tags"
   category = "categories"
   series = "series"

[[menu.main]]
   name = "Focus on work"
   weight = 2
   identifier = "Work"
   url = "/categories/work/"

[[menu.main]]
   name = "Programming"
   weight = 3
   identifier = "programming"
   url = "/categories/programming/"

[[menu.main]]
   name = "Pens and Notebooks"
   weight = 4
   identifier = "pens"
   url = "/categories/pens/"

[[menu.main]]
   name = "Creating Ideas"
   weight = 5
   identifier = "creativity"
   url = "/categories/creativity/"

[[menu.main]]
   name = "Future"
   weight = 6
   identifier = "future"
   url = "/categories/future/"

[[menu.main]]
   name = "Posts"
   weight = 10
   identifier = "posts"
   url = "/posts/"

[[menu.main]]
   name = "Microposts"
   weight = 12
   identifier = "microposts"
   url = "/microposts/"

