baseURL = "https://zeljko.dakic.com/"
languageCode = "en-us"
title = "Zeljko Dakic Is Doing Software In Chicago Blog"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Zeljko does software"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Zeljko Dakic Is Doing Software In Chicago Blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[author]
  name = "Zeljko Dakic"
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

# Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/desireco"

  [[params.social]]
    name = "email"
    url  = "mailto:zeljko@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/desireco"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/zeljkodakic"


[languages]
  [languages.en]
    title = "Hello World!"
    subtitle = 'Zeljko does software'
    homeMessage = "Read all about it!"
    keywords = ""
    copyright = ''
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = 'echo "Hello World!"'
      logoHomeLink = "/"


  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "short"
    name       = "Shorts"
    url        = "/microposts"

  [[menu.main]]
    identifier = "sites"
    name       = "Sites I ❤️"
    url        = "/sites"